#!/bin/bash -x

killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
for m in $(polybar --list-monitors | cut -d":" -f1); do
    PATH=~/.config/polybar/scripts:$PATH MONITOR=$m polybar -c ~/.config/polybar/config.ini main &
done