#!/bin/bash

desktop_env="default"
exclude_displays=()

OPTERR=0
while getopts "hd:e:" opt; do
  case $opt in
    h)
      usage
      exit
      ;;
    d)
      desktop_env=$OPTARG
      ;;
    e)
      exclude_displays+=($OPTARG)
      ;;
    \?)
      usage
      exit 1
    ;;
  esac
done

# Clear processed options
shift $((OPTIND-1))

killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

function get-role() {
  local monitor_name="$1"
  local role=`xrandr -q | grep -E '\bconnected' | grep $monitor_name | cut -d" " -f 3`
  if [ "$role" == "primary" ]; then
    echo -n "primary"
  else
    echo -n "secondary"
  fi
}

# Designed to work with https://github.com/adi1090x/polybar-themes
# For the monitor config to work the main bar config needs the following added:
# monitor = ${env:MONITOR}
for m in $(polybar --list-monitors | cut -d":" -f1); do
  if [[ " ${exclude_displays[@]} " =~ " ${m} " ]]; then
    echo "Ignoring ${m}." >&2
  else
    name=`echo $m | cut -d: -f1`
    role=`get-role $name`
    PATH=~/.config/polybar/scripts:$PATH MONITOR=$m MONITOR_ROLE=$role DESKTOP_ENV=$desktop_env polybar -c ~/.config/polybar/config.ini main &
  fi
done
